### ISSUE TITLE
Can't run npm start

### ISSUE THREAD

**Issue by Excalibrus** [mjhea0/typescript-node-api#1]
I can't run npm start, because i get an error that data.json can't be found in compiled js file. I tried many patch, but none of them work.

**Comment by hitamu** [comment]
A message log as bellow
```
Error: Cannot find module '../data'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/thunx/staff/typescript-node-api/dist/routes/HeroRouter.js:3:16)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```
That means `data.json` file could not be imported into `HeroRouter.js`.
The reason is `gulp` only transpire `*.ts` file and ignore `*.json`.
You can change this configure but maybe it'll be replaced soon.

So for able to start, I copied `data.json` from `src/data.json` to `dist/data.json` and it's worked!

**Comment by suh1986** [comment]
migrate data.json file from src to root folder and import in HeroRouter.ts like  this.
var Heroes = require('../../data');

**Comment by mjhea0** [comment]
Just updated the gulpfile to handle this.
